### PR TITLE
Don't return error from ReadResponseHeader

### LINKED ISSUE #63: "connection is shut down" issue occured again
hello, admin, it seems we see that the same issue occured again with latest codebase, originally you guys have fixed this, but later it seemed you added some code which reintroduced the issue again?

The code which caused this same issue now is the below code block(in client.go) per our understanding .

```
	if httpResponse.StatusCode < 200 || httpResponse.StatusCode >= 300 {
		return fmt.Errorf("request error: bad status code - %d", httpResponse.StatusCode)
	}
```

Based on our checking so far, when error returned from above code, the caller for loop breaks and client.shutdown is set to true and all following requests get failed.

Can you confirm this issue and if yes any plan to fix it? Thanks.

@kolo @miracle2k

### PR DESCRIPTION
**Pull request by icholy**
Fixes #63

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -31,7 +31,7 @@ type clientCodec struct {
 	responses map[uint64]*http.Response
 	mutex     sync.Mutex
 
-	response *Response
+	response Response
```
Comment (kolo) [inline client.go]: What is a reason for this change?

File: client.go [hunk 2]
```diff
@@ -84,47 +83,38 @@ func (codec *clientCodec) ReadResponseHeader(response *rpc.Response) (err error)
...
 
-	httpResponse.Body.Close()
-
-	resp := NewResponse(respData)
-
-	if resp.Failed() {
-		response.Error = fmt.Sprintf("%v", resp.Err())
+	resp := Response(body)
+	if err := resp.Err(); err != nil {
+		response.Error = err.Error()
```
Comment (kolo) [inline client.go]: If I see it correctly we might override error which is set in line 96 here. `ioutil.ReadAll` might return `nil` and an error. In this case we will call `resp.Err()` on an nil slice which will return unmarshalling error.

File: client.go [hunk 3]
```diff
@@ -84,47 +83,38 @@ func (codec *clientCodec) ReadResponseHeader(response *rpc.Response) (err error)
...
 	codec.mutex.Unlock()
 
 	if httpResponse.StatusCode < 200 || httpResponse.StatusCode >= 300 {
-		return fmt.Errorf("request error: bad status code - %d", httpResponse.StatusCode)
+		response.Error = fmt.Sprintf("request error: bad status code - %d", httpResponse.StatusCode)
 	}
 
-	respData, err := ioutil.ReadAll(httpResponse.Body)
-
+	defer httpResponse.Body.Close()
```
Comment (kolo) [inline client.go]: We can close response body immideately atfer calling `ioutil.ReadAll`. I don't see much benefit of using `defer` here.

File: client.go (hunk 1 above)
Comment (icholy) [reply client.go]: @kolo `Response` is just a slice of bytes so I removed the unnecessary wrapping `struct`. Since slices are already reference types, there's no need to make it a pointer.

Comment (icholy) [reply client.go]: I can split these up into separate PRs if you want.

File: client.go [hunk 4]
```diff
@@ -84,47 +83,42 @@ func (codec *clientCodec) ReadResponseHeader(response *rpc.Response) (err error)
...
 	if httpResponse.StatusCode < 200 || httpResponse.StatusCode >= 300 {
-		return fmt.Errorf("request error: bad status code - %d", httpResponse.StatusCode)
+		response.Error = fmt.Sprintf("request error: bad status code - %d", httpResponse.StatusCode)
 	}
 
-	respData, err := ioutil.ReadAll(httpResponse.Body)
-
+	body, err := ioutil.ReadAll(httpResponse.Body)
 	if err != nil {
-		return err
```
[the remark this answers is not in the document]
Comment (icholy) [reply client.go]: It needed to set `response.Seq`, but I've moved that to the top now.

**Comment by icholy** [comment]
@sonic0002 can you confirm this branch fixes your issue?

File: encoder.go [hunk 5]
```diff
@@ -10,6 +10,9 @@ import (
 	"time"
 )
 
+// Base64 represents value in base64 encoding
+type Base64 string
```
Comment (kolo) [inline encoder.go]: I don't see there this type is used? Do we need it?

Comment (icholy) [reply encoder.go]: @kolo encoder.go:70
